version: '3'
services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: costs-to-expect-web-app
        ports:
        - 80:80
        volumes:
        - .:/.docker/app/php
